apiVersion: apps/v1
kind: Deployment
metadata:
  name: inv-integration-layer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inv-integration-layer
  template:
    metadata:
      labels:
        app: inv-integration-layer
    spec:
      containers:
      - name: inv-integration-layer        
        image: sagar01acr.azurecr.io/invintegrationlayer:v1
        imagePullPolicy: Always
        resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
        ports:
        - containerPort: 8080
